### PR TITLE
Taking a stab at adding some messages and importing them into the bot

### PR DESCRIPTION
**Pull request by ElliotFriend**
I've gotten this to work in my testing discord server, and it's looking
to me like it's working.

Please review this, I'm not well-versed in discord and/or bot programming.

Signed-off-by: Elliot Voris <elliot@voris.me>

### CODE REVIEW

**Comment by Smephite** [comment]
Did you test these changes with a discord bot?

Wil discord allow you to enter the command ignoring case or will this force us to execute `/COMMAND` (upper case)?

Either way: I would suggest adding a to_lower_case such that the discord auto-completion will complete the commands in lower case.

Else: LGTM!

**Comment by ElliotFriend** [comment]
Tested it on my own discord bot. Everything looked lowercase (both in the entry box, and in the message history) in discord. Thanks for the feedback!

**Review by Smephite — APPROVED** [review]

**Review by matthew-graves — APPROVED** [review]
Approved

**Review by MatejMecka — APPROVED** [review]
LGTM!

**Pull request merged**
